name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, 386, arm64]
        exclude:
          - os: darwin
            arch: 386
          - os: windows
            arch: arm64

    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Code
        run: go build -o build/terraform-backend-http-proxy-${{ matrix.os }}-${{ matrix.arch }}
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
