name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, 386, arm64]
        exclude:
          - os: darwin
            arch: 386
          - os: windows
            arch: arm64

    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Set RELEASE_VERSION
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: Set RELEASE_STRING
        run: echo "RELEASE_STRING=v${RELEASE_VERSION}" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Add Windows Exe File Extension
        if: matrix.os == 'windows'
        run: echo "FILE_EXTENSION=.exe" >> $GITHUB_ENV

      - name: Build Code
        run: go build -ldflags="-X 'terraform-backend-http-proxy/cmd.Version=${{ env.RELEASE_STRING }}'" -o build/terraform-backend-http-proxy-${{ matrix.os }}-${{ matrix.arch }}${{ env.FILE_EXTENSION }}
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: terraform-backend-http-proxy
          path: build/terraform-backend-http-proxy-${{ matrix.os }}-${{ matrix.arch }}${{ env.FILE_EXTENSION }}

  release:
    name: Draft Release
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: terraform-backend-http-proxy
          path: terraform-backend-http-proxy

      - name: Generate SHA256SUMS
        run: cd terraform-backend-http-proxy && sha256sum * > SHA256SUMS

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            terraform-backend-http-proxy/*